version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: alghadeer-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: alghadeer123
      MONGO_INITDB_DATABASE: alghadeer_events
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - alghadeer-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: alghadeer-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:alghadeer123@mongodb:27017/alghadeer_events?authSource=admin
      - DATABASE_NAME=alghadeer_events
      - SECRET_KEY=your-secret-key-change-this-in-production-min-32-chars
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - alghadeer-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: alghadeer-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - alghadeer-network
    command: npm run dev

  # Redis for Caching (Optional)
  redis:
    image: redis:7-alpine
    container_name: alghadeer-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - alghadeer-network
    command: redis-server --appendonly yes

networks:
  alghadeer-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local